<?php return array (
  '-' => 
  array (
    'allow_negative_amount' => 'Y',
    'allowed_currencies' => 'USD',
    'allowed_group_fields' => 'IC_GROUP',
    'allowed_price_fields' => 'CV_PRICE,CV_CURRENCY',
    'allowed_product_fields' => 'IE_XML_ID,IE_NAME,IE_PREVIEW_TEXT,IE_DETAIL_TEXT,CP_QUANTITY,CP_WEIGHT,CP_WIDTH,CP_HEIGHT,CP_LENGTH',
    'avail_content_groups' => '',
    'deactivate_1c_no_price' => 'N',
    'default_can_buy_zero' => 'Y',
    'default_catalog_1c' => '',
    'default_outfile_action' => 'D',
    'default_product_vat_included' => 'Y',
    'default_quantity_trace' => 'Y',
    'default_subscribe' => 'Y',
    'default_use_store_control' => 'Y',
    'enable_processing_deprecated_events' => 'N',
    'enable_reservation' => 'Y',
    'enable_viewed_products' => 'Y',
    'export_default_path' => '/bitrix/catalog_export/',
    'group_default_right' => 'D',
    'group_default_task' => '24',
    'num_catalog_levels' => '3',
    'product_form_show_offer_name' => 'N',
    'product_form_show_offers_iblock' => 'N',
    'product_form_simple_search' => 'Y',
    'save_product_with_empty_price_range' => 'N',
    'save_product_without_price' => 'Y',
    'show_catalog_tab_with_offers' => 'N',
    'show_store_shipping_center' => 'N',
    'subscribe_repeated_notify' => 'Y',
    'use_offer_marking_code_group' => 'N',
    'viewed_count' => '10',
    'viewed_period' => '5',
    'viewed_time' => '10',
    'yandex_agent_file' => '',
    'yandex_xml_period' => '24',
  ),
);
