<?php
/**
 * Настройки модуля по умолчанию
 *
 * Список hidden_modules содержит модули маркетплейса, которые следует скрыть
 * из списка проверки обновлений (модули сторонних разработчиков)
 */
$itnull_updater_default_option = [
    'hidden_modules' => 'acrit.1cexch
acrit.catprice
acrit.cleanmaster
acrit.document
acrit.examination
acrit.export
acrit.exportnews
acrit.exportpro
acrit.exportproplus
acrit.goodssubscribe
acrit.googlemerchant
acrit.import
acrit.seo
acrit.voicesearch
aistweb.lpservice
alexkova.adback
alexkova.business
alexkova.corporate
alexkova.emarket
alexkova.fstart
alexkova.market
alexkova.market2
alexkova.popupad
alexkova.rklite
alexkova.seoimage
altasib.abc
altasib.authforms
altasib.autodiscount
altasib.cmylog
altasib.comments
altasib.discountcounter
altasib.discounts
altasib.docslist
altasib.float
altasib.floataction
altasib.floatlabel
altasib.geobase
altasib.guestbook
altasib.imagebox
altasib.invitereg
altasib.ireception
altasib.nav
altasib.paidreg
altasib.ping
altasib.relink2
altasib.remind
altasib.reservation
altasib.review
altasib.salebasketlink
altasib.scrollgoods
altasib.sendpass
altasib.simplevote
altasib.subscribe
altop.elastominimarket
altop.elastostart
altop.elektroinstrument
altop.enext
ambersite.autoresizer
ambersite.evento
ambersite.gridportfolio
ambersite.independentmetatags
ambersite.popupforms
ambersite.prostosite
ambersite.quickpay
ambersite.smartdownload
ambersite.timetable
apsel.comod
apsel.liteshop
apsel.multi
apsel.multilight
apsel.multishop
apsel.puzzle
apsel.puzzleplus
apsel.shipping
apsel.slide
apsel.studio
apsel.studiolight
aqw.video
artdepo.bumblebee
artdepo.gallery
artdepo.notifybar
artdepo.sideswipe
artdepo.sideswipecatalog
asd.affiliatestat
asd.amchartsvote
asd.colororder
asd.isale
asd.metrika
asd.moderator
asd.money
asd.orderprint
asd.orderservices
asd.ordertracking
asd.seo
asd.sitemap
asd.taskslog
askaron.attributes1c
askaron.deals
askaron.fastprice
askaron.freespace
askaron.geo
askaron.handlers1c
askaron.include
askaron.kpidrive
askaron.mailmanager
askaron.pricename
askaron.pro1c
askaron.productlog
askaron.reviews
askaron.sections1c
askaron.shredder
askaron.sitemap
askaron.slow
askaron.traits1c
askaron.urlpay
askaron.workingtimechart
aspro.allcorp
aspro.allcorp2
aspro.corporation
aspro.creditcalc
aspro.digital
aspro.import
aspro.ishop
aspro.kshop
aspro.landscape
aspro.max
aspro.medc2
aspro.medcenter
aspro.mshop
aspro.next
aspro.optimus
aspro.priority
aspro.resort
aspro.scorp
aspro.stroy
aspro.tires
aspro.tyrecalc
bagmet.landingstor
bagmet.landingstore
bagmet.menu
bd.burgers
bd.convertshop
bd.deliverypizza
bd.deliverysushi
bd.niceceiling
bitfactory.opengraph
bizsolutions.alpha
bizsolutions.alphalanding
bizsolutions.alphalight
bizsolutions.autoservice
bizsolutions.basis
bizsolutions.clever
bizsolutions.factory
bizsolutions.mohito
bizsolutions.mohitolanding
bizsolutions.mohitolight
bizsolutions.orgmedica
bizsolutions.sms
bizsolutions.talkme
bizsolutions.unique
boxsol.adaptivebusiness
boxsol.astra
boxsol.bitcorp
boxsol.cosmofashion
boxsol.cosmoland
boxsol.cosmopro
boxsol.cosmos
boxsol.cosmoshop
boxsol.cosmostroy
boxsol.focus
boxsol.mozy
boxsol.optima
boxsol.smart
burbon.firstlanding
burbon.greenparrot
burbon.landing
bxmaker.ajaxpagenav
bxmaker.ap
bxmaker.authuserphone
bxmaker.geoip
bxmaker.log
bxmaker.shortlink
bxmaker.smscampaign
bxmaker.smsnotice
bxmaker.vk
capital.magazin
capital.magazinlite
citfact.clothing
citfact.deliverysport
citfact.deliverytech
citfact.deliveryzoo
citfact.getfood
citfact.podarkilight
citrus.aproduction
citrus.aproduction2
citrus.arealty
citrus.arealtypro
citrus.developer
citrus.materials
citrus.production
citrus.realty
citrus.reformagkh
concept.banner
concept.hameleon
concept.headshot
concept.kraken
concept.phoenix
concept.quiz
ctweb.instauth
ctweb.managerdelivery
ctweb.messengers
ctweb.sendpush
ctweb.smsauth
ctweb.smsreceipt
ctweb.socgroupverify
ctweb.yandexdelivery
denisoft.pushone
doninbiz.fortis
doninbiz.liberty
dw.deluxe
dw.electro
edost.catalogdelivery
edost.locations
esol.importexportexcel
esol.importorders
esol.importxml
esol.massedit
flysign.massmedia
foxtheme.buchalter
gorillas.alfabank
gorillas.callback
gorillas.dadata
gorillas.dadataadmin
gorillas.dadatagran
gorillas.dadatagranadmin
gorillas.glavpunkt
gorillas.ims
gorillas.paymill
gorillas.saleproduct
gorillas.sort
gorillas.tvoyshop
gvozdevsoft.ant
gvozdevsoft.avto
gvozdevsoft.bober
gvozdevsoft.event
gvozdevsoft.fakel
gvozdevsoft.foton
gvozdevsoft.gskorp
gvozdevsoft.gsremont
gvozdevsoft.gsstroy
gvozdevsoft.hotel
gvozdevsoft.kulibin
gvozdevsoft.moda
gvozdevsoft.pila
gvozdevsoft.remont
gvozdevsoft.universal
gvozdevsoft.unpro
idf.aboutlanding
idf.exportimportcsv
idf.exportprice
idf.flatlanding
idf.insta
idf.massimport
idf.notelanding
idf.stylestic
informteh.selo
informteh.selpo
infospice.shoplogisticsd7
innet.build2
innet.corp
innet.corp2
innet.corp4
innet.focus
innet.gifts2
innet.house2
innet.kids2
innet.market
innet.office2
innet.plumbing2
innet.sport2
innet.tourism2
innet.zoo2
intec.adapthgarderob
intec.chatbot
intec.constructor
intec.landingconstructor
intec.matilda
intec.startshop
intec.unigarderob
intec.unimagazin
intec.unimagazinlite
intec.unisite
intec.universe
intec.universelite
intec.universesite
intels.hotel
intels.restaurant
intels.shop
intels.sliderresponsive2
intervolga.conversion
intervolga.conversionpro
intervolga.copyright
intervolga.enrich
intervolga.mailtools
intervolga.menu
intervolga.recaptcha
intervolga.retargeting
intervolga.seo
intervolga.seofilters
intervolga.smo
intervolga.tips
ipgraph.mymap
ipol.aseo
ipol.auen
ipol.ddelivery
ipol.kladr
ipol.mshp
ipol.ordertime
ipol.pcpy
ipol.prodhist
ipol.quasorter
ipol.yadost
ithive.amchartscomponent
ithive.crmgridtetrishistory
ithive.hlblock
ithive.iboard
ithive.jewelshop
ithive.musicshop
ithive.officesplus
ithive.sciencemagazine
ithive.universalcatalog
ithive.universallite
itserw.kuponnik
justmozg.abc
kolored.insta
kolored.instapro
kolored.thebarber
kombox.filter
krivovnet.contentbeautitable
krivovnet.mrocketpopup
krivovnet.preloader
kssite.jksbooklet
kssite.jksfeedbackajax
kssite.jksgallery
kssite.jksgallerynews
kssite.jksimagebox
kssite.jksincludenicescroll
kssite.jksmapoffices
kssite.jksnewseffects
kssite.jksnewseffects2
kssite.jksnewseffects3
kssite.jksnewseffects4
kssite.jksnewseffects5
kssite.jksnewseffects6
kssite.jksnewseffectscircle
kssite.jksnewseffectsicons
kssite.jksnewsslider
kssite.jksnewsslidercslider
kssite.jksnewssliderjcarousel
kssite.jksnewsslidermobil
kssite.jksnewsslidernivo
kssite.jksnewssmoothslider
kssite.jksnewstiltedslideshow
kssite.jksnewswowslider
kssite.jksnewswowsliderfulllength
kssite.jkssociallikes
kssite.jkstimer
kssite.jkstimercircle
kssite.ksalbums
kssite.ksphotoalbum
kssite.sliderfulllength
lenal.pricechanger
lenal.tictac
linemedia.api
linemedia.auto
linemedia.autoanalogssimple
linemedia.autobranches
linemedia.autodownloader
linemedia.autogarage
linemedia.autoglass
linemedia.automodifier
linemedia.autooil
linemedia.autooriginalcatalogs
linemedia.autoprice
linemedia.autoremotesuppliers
linemedia.autosphinx
linemedia.autosuppliers
linemedia.autotecdoc
linemedia.autoto
linemedia.autotyres
linemedia.seo
mibix.minorder
ms.active
ms.corpsite
ms.evolution
ms.ubershop
ms.universal
nsandrey.crossposting
nsandrey.easyprofile
nsandrey.messagespy
nsandrey.quiz
nsandrey.sitemap
nulled.autoservice
pilabs.sbr
primelab.activelife
primelab.autocity
primelab.oneclickbuy
primelab.paysystembillua
primelab.photographe
primelab.popupcupon
primelab.proopt
primelab.supershop
primelab.urltosef
primepix.catalog2vk
primepix.catalog2vkpro
primepix.catalogreport
primepix.fitnessplus
primepix.merlion
primepix.merlionorders
primepix.minipizza
primepix.phototool
primepix.pipedrivecrm
primepix.propertygroups
primepix.propertylink
primepix.propertytoolkit
primepix.showcasenetlab
primepix.sport
qwelp.excorpo
qwelp.workshop
redsign.activelife
redsign.autocity
redsign.daysarticle2
redsign.devcom
redsign.devfunc
redsign.easycart
redsign.everyday
redsign.fashionshow
redsign.favorite
redsign.flyaway
redsign.gotravel
redsign.homeware
redsign.landing
redsign.location
redsign.lovekids
redsign.massmedia
redsign.master
redsign.media
redsign.mediamart
redsign.monopoly
redsign.mshop
redsign.officespace
redsign.oneair
redsign.pethouse
redsign.proauto
redsign.profashion
redsign.profood
redsign.profurniture
redsign.progmarket
redsign.prohome
redsign.prokids
redsign.prooffice
redsign.proopt
redsign.prosport
redsign.prostroy
redsign.prozoo
redsign.recaptcha
redsign.stroymart
romza.atlantic
romza.ocean
romza.widgetinstagram
sebekon.cargoprice
sebekon.catalogschemes
sebekon.comments
sebekon.deliveryprice
sebekon.filedownloader
sebekon.filestorage
sebekon.ftpbackup
sebekon.help
sebekon.hhvacancies
sebekon.notary
sebekon.presents
sebekon.psbpayment
sebekon.reminder
sebekon.remindme
sebekon.yandexfastorder
sebekon.yandexpost
sergeland.businessweb
sergeland.effortless
sergeland.effortlesslight
sergeland.elbrus
sergeland.elbruslight
sergeland.felice
sergeland.fuzzbot
sergeland.galaxy
sergeland.metso
sergeland.metsolight
sergeland.retail
sergeland.shopping
sergeland.shoppingstart
sergeland.sphinx
sergeland.sphinx2
sergeland.sphinxlight
sergeland.streetstyle
sergeland.switcher
sergeland.ultimate
shs.hh
shs.parser
sideas.veranda
skyweb24.alreadygoing
skyweb24.buymore
skyweb24.itinerarycourier
skyweb24.popuppro
skyweb24.statorders
sms.sstudio
sns.tools1c
softinfo.advstat
softinfo.ears
sokrat.lastmodified
sokrat.subelement
sokrat.yadisk
soobwa.commentspro
sotbit.accountant
sotbit.analog
sotbit.auth
sotbit.b24generator
sotbit.b2bshop
sotbit.bill
sotbit.cabinet
sotbit.checkcompany
sotbit.crmbitrix24
sotbit.crmtools
sotbit.discountregister
sotbit.elba
sotbit.htmleditoraddition
sotbit.instagram
sotbit.mailing
sotbit.missshop
sotbit.mistershop
sotbit.postcalc
sotbit.price
sotbit.regions
sotbit.reviews
sotbit.seometa
sotbit.seosearch
sotbit.siteremont
sotbit.wikimartorders
sotbit.yandex
step2use.redirects
step2use.uniteller
top10.callbackwithrange
twozebras.dengionline
twozebras.interkassa
vampirus.yandex
vbcherepanov.bonus
vbcherepanov.callback
vbcherepanov.cleaner
vbcherepanov.couponmask
vbcherepanov.importuser
vbcherepanov.mobidel
vbcherepanov.ordertoamo
webdebug.antirutin
webdebug.artim
webdebug.beautysalon
webdebug.belmru
webdebug.catalogtree
webdebug.discount
webdebug.excel
webdebug.giftsru
webdebug.image
webdebug.import
webdebug.marque
webdebug.multislider
webdebug.p5s
webdebug.popup
webdebug.redirector
webdebug.reviews
webdebug.save2pdf
webdebug.siteflowers
webdebug.sms
webdebug.undelete
webfly.axiomus
webfly.bitlite
webfly.buyit
webfly.gmerchant
webfly.instagram
webfly.pickpoint
webfly.santech
webfly.sbrf
webfly.schemaorg
webfly.seocities
webfly.taxi
webfly.ymarket
webfly.yrealty
webmaxima.expxls
webmaxima.sushi
webme.trucking
webstudiosamovar.businessbuy
webstudiosamovar.odsmarket
webstudiosamovar.otel
webstudiosamovar.otelbron
webstudiosamovar.realty
webstudiosamovar.remontsw
webstudiosamovar.remstroy
webstudiosamovar.servicecar
webstudiosamovar.smarket
webstudiosamovar.sservice
webstudiosamovar.stroykas
webstudiosamovar.sushi
webstudiosamovar.yrist
westpower.youtube
wsm.banners
wsm.bonus
wsm.city
wsm.favorites
wsm.gallery
wsm.import1c
wsm.import1clog
wsm.mapoffices
wsm.notice
wsm.reviews
wsm.youtubeprop
xon.beef
yenisite.abcd
yenisite.apparel
yenisite.apparellite
yenisite.b2acc
yenisite.b2apparel
yenisite.b2art
yenisite.b2bag
yenisite.b2beauty
yenisite.b2car
yenisite.b2drug
yenisite.b2electro
yenisite.b2fastfood
yenisite.b2flower
yenisite.b2food
yenisite.b2furniture
yenisite.b2gift
yenisite.b2glass
yenisite.b2gun
yenisite.b2intim
yenisite.b2jewelry
yenisite.b2kre
yenisite.b2light
yenisite.b2oil
yenisite.b2pet
yenisite.b2shin
yenisite.b2signal
yenisite.b2sound
yenisite.b2sport
yenisite.b2tao
yenisite.b2tools
yenisite.b2toy
yenisite.b2watch
yenisite.b2wines
yenisite.basketfly
yenisite.bbs
yenisite.bbsauto
yenisite.bbsjobs
yenisite.bbslite
yenisite.beautyshop
yenisite.bitronic2
yenisite.bitronic2lite
yenisite.bitronic2pro
yenisite.catchbuy
yenisite.core
yenisite.coreparser
yenisite.fastfood
yenisite.fastfoodlite
yenisite.favorite
yenisite.feedback
yenisite.filter
yenisite.furniture
yenisite.furniturelite
yenisite.geoip
yenisite.geoipstore
yenisite.googlecaptcha
yenisite.gyroscooter
yenisite.iblockadd
yenisite.infoblockpropsplus
yenisite.landing
yenisite.mainspec
yenisite.market
yenisite.menu
yenisite.meta
yenisite.migrator
yenisite.oneclick
yenisite.onlinestore
yenisite.pricegen
yenisite.profileadd
yenisite.realty
yenisite.resizer2
yenisite.searcher
yenisite.seofilter
yenisite.shinmarket
yenisite.shinmarketlite
yenisite.shinmarketpro
yenisite.specifications
yenisite.storeamount
yenisite.stroymag
yenisite.stroymaglite
yenisite.toystorelite
yenisite.unova
yenisite.upro
yenisite.uproultra
yenisite.yandex
yenisite.yandexreviewsmodel
yenisite.ymrs
zixo.blanks',
];
