<?php return array (
  '-' => 
  array (
    'agent_duration' => '2',
    'agent_stemming' => 'N',
    'dbnode_id' => 'N',
    'dbnode_status' => 'ok',
    'exclude_mask' => '/bitrix/*;/404.php;/upload/*;*/.hg/*;*/.svn/*;*/.git/*;*/cgi-bin/*;/bitrix_personal/*;/local/*',
    'full_text_engine' => 'sphinx',
    'include_mask' => '*.php;*.html;*.htm',
    'letters' => '-',
    'max_body_size' => '512',
    'max_execution_time' => '3',
    'max_file_size' => '',
    'max_result_size' => '500',
    'mysql_note' => NULL,
    'opensearch_analyzer' => NULL,
    'opensearch_analyzer_s1' => 'russian',
    'opensearch_connection' => '',
    'opensearch_index' => '',
    'opensearch_user' => '',
    'page_tag_property' => 'tags',
    'sm_blog_no_comments' => 'N',
    'sm_forum_topics_only' => 'N',
    'sm_max_execution_time' => '30',
    'sm_record_limit' => '5000',
    'sm_use_https' => 'Y',
    'sphinx_connection' => '127.0.0.1:9306',
    'sphinx_index_name' => 'bitrix',
    'sphinx_note' => NULL,
    'stat_phrase' => 'N',
    'stat_phrase_save_days' => '360',
    'suggest_save_days' => '250',
    'use_social_rating' => 'N',
    'use_stemming' => 'Y',
    'use_tf_cache' => 'Y',
    'use_word_distance' => 'Y',
  ),
);
